const express = require('express')
const {protect}=require('../middleware/auth')

const router = express.Router();
const{addStudent,students,deleteStudent,updateStudent,getStudent,promote,findStudent,transfer,studentsData,deleteSection,totalStudents,totalClasses,totalSections}=require('../controller/Acadmic/student.controller')
router.route('/addStudent').post(addStudent)
router.route('/students').get(students)
router.route('/totalStudents').get(totalStudents)
router.route('/totalClasses').get(totalClasses)
router.route('/totalSections').get(totalSections)
router.route('/deleteSection').delete(deleteSection)

router.route('/studentsData').get(studentsData)
router.route('/student').get(getStudent)
router.route('/findStudent').get(findStudent)
router.route('/student').delete(deleteStudent)
router.route('/updateStudent/:id').put(updateStudent)
router.route('/promote').post(promote)
router.route('/transfer').post(transfer)
const{addNotice,notices,deleteNotice,updateNotice,getNotice}=require('../controller/Acadmic/noticeboard.controller')
router.route('/addNotice').post(addNotice)
router.route('/notices').get(notices)
router.route('/notice').get(getNotice)
router.route('/notice').delete(deleteNotice)
router.route('/updateNotice/:id').put(updateNotice)
const{addHomework,homeworks,deleteHomework,updateHomework,getHomework}=require('../controller/Acadmic/homework.controller')
router.route('/addHomework').post(addHomework)
router.route('/homeworks').get(homeworks)
router.route('/homework').get(getHomework)
router.route('/homework').delete(deleteHomework)
router.route('/updateHomework/:id').put(updateHomework)
const {sendEmail}=require('../controller/Acadmic/email.controller')
router.route('/sendEmail').post(sendEmail)
// const {Upload,upload}=require('../controller/Acadmic/upload.controller')
// router.post('/uploads', upload,Upload)
const{addIncome,incomes,deleteIncome,deleteIncomeRecord,updateIncome
    ,getIncome,incomeDashboard,incomeReport,incomeReportRole}=require('../controller/Acadmic/income.controller')
router.route('/addIncome').post(addIncome)
router.route('/incomes').get(incomes)
router.route('/income').get(getIncome)
router.route('/income').delete(deleteIncome)
router.route('/deleteIncome').delete(deleteIncomeRecord)
router.route('/updateIncome/:id').put(updateIncome)
router.route('/incomeDashboard').get(incomeDashboard)
router.route('/incomeReport').get(incomeReport)

router.route('/incomeReportRole').get(incomeReportRole)
const{addExpense,Expenses,deleteExpense,deleteExpenseRecord,updateExpense,getExpense,expenseDashboard,expenseReport,expenseReportRole}=require('../controller/Acadmic/expense.controller')
router.route('/addExpense').post(addExpense)
router.route('/Expenses').get(Expenses)
router.route('/Expense').get(getExpense)
router.route('/Expense').delete(deleteExpense)
router.route('/deleteExpense').delete(deleteExpenseRecord)
router.route('/updateExpense/:id').put(updateExpense)
router.route('/expenseDashboard').get(expenseDashboard)
router.route('/expenseReport').get(expenseReport)

router.route('/expenseReportRole').get(expenseReportRole)
const{addFee,fees,deleteFee,getFee,getDeposite,generateFee,payFee,feeDashboard,
    feeReport,feeReportExpensive,feeFineReport,deleteFeeRecord,feeGeneralReport,feeR2f1,feeReportRole}=require('../controller/Acadmic/fee.controller')
router.route('/addFee').post(addFee)
router.route('/fees').get(fees)
router.route('/fee').get(getFee)
router.route('/feeDeposite').get(getDeposite)
router.route('/feeDashboard').get(feeDashboard)
router.route('/fee').delete(deleteFee)
router.route('/deleteFee').delete(deleteFeeRecord)
router.route('/generateFee').post(generateFee)
router.route('/payFee').post(payFee)
router.route('/feeReport').get(feeReport)
router.route('/feeReportExpensive').get(feeReportExpensive)
router.route('/feeGeneralReport').get(feeGeneralReport)
router.route('/feeFineReport').get(feeFineReport)
router.route('/feeR2f1').get(feeR2f1)
router.route('/feeReportRole').get(feeReportRole)
const{addSalary,salaries,deleteSalary,getSalary,salaryR2f1,deleteSalaryRecord,getSalaryDeposite,generateSalary,paySalary,salaryDashboard,salaryStaffReport,salaryReport,salaryGeneralReport,salaryReportRole}=require('../controller/Acadmic/salary.controller')
router.route('/addSalary').post(addSalary)
router.route('/salaries').get(salaries)
router.route('/salary').get(getSalary)
router.route('/salaryR2f1').get(salaryR2f1)
router.route('/salaryDeposite').get(getSalaryDeposite)
router.route('/salary').delete(deleteSalary)
router.route('/deleteSalary').delete(deleteSalaryRecord)
router.route('/generateSalary').post(generateSalary)
router.route('/paySalary').post(paySalary)
router.route('/salaryDashboard').get(salaryDashboard)
router.route('/salaryReport').get(salaryReport)
router.route('/salaryGeneralReport').get(salaryGeneralReport)
router.route('/salaryReportRole').get(salaryReportRole)
router.route('/salaryStaffReport').get(salaryStaffReport)

const{addMessage,messages,deleteMessage}=require('../controller/Acadmic/message.controller')
router.route('/addMessage').post(addMessage)
router.route('/messages').get(messages)
router.route('/message').delete(deleteMessage)
// user Attendance
const {markAttendance,getAttendance,updateAttendance,viewAttendance,deleteAttendanceRecord}=require('../controller/Acadmic/userAttendance.controller')
router.route('/markAttendance').post(markAttendance)
router.route('/getAttendance').get(getAttendance)
router.route('/updateAttendance').put(updateAttendance)
router.route('/viewAttendance').get(viewAttendance)
router.route('/deleteAttendanceRecord').delete(deleteAttendanceRecord)
// student Attendance markStudentAttendance
const {markStudentAttendance,getStudentAttendance,updateStudentAttendance,viewStudentAttendance,deleteStudentAttendanceRecord}=require('../controller/Acadmic/studentAttendance')
router.route('/markStudentAttendance').post(markStudentAttendance)
router.route('/getStudentAttendance').get(getStudentAttendance)
router.route('/updateStudentAttendance').put(updateStudentAttendance)
router.route('/viewStudentAttendance').get(viewStudentAttendance)
router.route('/deleteStudentAttendanceRecord').delete(deleteStudentAttendanceRecord)

//Exam
const{addExam,exams,deleteExam,getExam}=require('../controller/Acadmic/exam.controller')
router.route('/addExam').post(addExam)
router.route('/exams').get(exams)
router.route('/exam').get(getExam)
router.route('/exam').delete(deleteExam)


const { SuperAdmin } = require('../controller/super_admin/index')
router.route('/addClass').post(SuperAdmin.addClass)
//router.route('/addStudent').post(SuperAdmin.addStudent)
router.route('/addSection').post(SuperAdmin.addSection)
router.route('/getClasses').get(SuperAdmin.getClasses)
router.route('/getSections').get(SuperAdmin.getSections)
router.route('/classData').get(SuperAdmin.classData)
router.route('/sectionData/:id').get(SuperAdmin.sectionData)
router.route('/singleClass/:id').get(SuperAdmin.singleClass)
router.route('/singleSection/:id').get(SuperAdmin.singleSection)
router.route('/updateSection/:id').post(SuperAdmin.updateSection)
router.route('/deleteSection/:id').delete(SuperAdmin.deleteSection)
//router.route('/deleteStudent/:id').delete(SuperAdmin.deleteStudent)
router.route('/changeSections/:title').get(SuperAdmin.changeSections)
router.route('/GradeTitles/:title').get(SuperAdmin.GradeTitles)
router.route('/GradeTitlesByClass/:title').get(SuperAdmin.GradeTitlesByClass)
router.route('/getStudents/:title').get(SuperAdmin.getStudents)
//router.route('/submitAttendance').post(SuperAdmin.submitAttendance)
//router.route('/viewAttendance/:title_s/:title_c').get(SuperAdmin.viewAttendance)
//router.route('/editAttendance/:date').post(SuperAdmin.editAttendance)
router.route('/singleStudent/:id').get(SuperAdmin.singleStudent)
router.route('/singleStudentByRoll/:id').get(SuperAdmin.singleStudentByRoll)
router.route('/addStudentGrade/').post(SuperAdmin.addStudentGrade)
router.route('/getStudentGrades/:id').get(SuperAdmin.getStudentGrades)
router.route('/classGrades/:title_1/:title_2').get(SuperAdmin.classGrades)
router.route('/classGradesBySection/:title_1/:title_2/:title_3').get(SuperAdmin.classGradesBySection)
router.route('/getGradestitles/:id').get(SuperAdmin.getGradestitles)
router.route('/getStudentGrades/:id').get(SuperAdmin.getStudentGrades)
router.route('/updateGrade/:id').post(SuperAdmin.updateGrade)
router.route('/deleteGrade/:id').delete(SuperAdmin.deleteGrade)
router.route('/singleGrade/:id').get(SuperAdmin.singleGrade)
router.route('/addLecture').post(SuperAdmin.addLecture)
router.route('/getTimetable').get(SuperAdmin.getTimetable)
router.route('/updateTimetable/:id').post(SuperAdmin.updateTimetable)
router.route('/deleteTimetable/:id').delete(SuperAdmin.deleteTimetable)
router.route('/updateTimetable/:id').delete(SuperAdmin.updateTimetable)
router.route('/singleTimetable/:id').get(SuperAdmin.singleTimetable)
//router.route('/getDayAttendance/:title_s/:title_c/:id').get(SuperAdmin.getDayAttendance)
router.route('/getDataCount').get(SuperAdmin.getDataCount)
router.route('/deleteClass/:id').delete(SuperAdmin.deleteClass)
router.route('/updateClass/:id').post(SuperAdmin.updateClass)

module.exports= router